{{- if or (.Values.minAvailable) (.Values.maxUnavailable) }}
{{- if .Capabilities.APIVersions.Has "policy/v1" -}}
apiVersion: policy/v1
{{- else}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "akeyless-api-gw.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akeyless-api-gw.labels" . | nindent 4 }}
  {{- if .Values.service.labels }}
  {{- toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  {{- if .Values.minAvailable}}
  minAvailable: {{ .Values.minAvailable }}
  {{- else if .Values.maxUnavailable }}
  maxUnavailable: {{ .Values.maxUnavailable }}
  {{- end }}
  selector:
    { { - include "akeyless-api-gw.selectorLabels" . | nindent 4 } }
  {{- end }}
